---
image:
    name: dimtass/stm32-cde-image:0.1
    entrypoint: [""]

variables:
    GIT_SUBMODULE_STRATEGY: recursive

stages:
    - build
    - test

build:
    stage: build
    script: time TOOLCHAIN_DIR=/opt/toolchains/gcc-arm-none-eabi-9-2019-q4-major CLEANBUILD=true USE_STDPERIPH_DRIVER=ON SRC=src_stdperiph ./build.sh
    cache:
        key: build-cache
        paths:
        - build-stm32/src_stdperiph
    artifacts:
        paths:
        - build-stm32/src_stdperiph/stm32-cmake-template.bin
        expire_in: 1 week

test:
    stage: test
    script: file build-stm32/src_stdperiph/stm32-cmake-template.bin
    cache:
        key: build-cache