---
    image:
      name: dimtass/stm32-cde-image:0.1
      entrypoint: [""]
    
    variables:
      GIT_SUBMODULE_STRATEGY: none
    
    stages:
      - build
      - test
    
    build:
      stage: build
      script: TOOLCHAIN_DIR=/opt/toolchains/gcc-arm-none-eabi-9-2019-q4-major CLEANBUILD=true USE_STDPERIPH_DRIVER=ON SRC=src_stdperiph ./build.sh
    
    test:
      stage: test
      script: echo "Dummy tests are done..."